### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KarlG-03** [keijiro/Retro3DPipeline#1]
RenderTexture.Create failed: format unsupported - 4.
UnityEngine.Experimental.Rendering.ScriptableRenderContext:Submit()
Retro3D.Retro3DPipeline:Render(ScriptableRenderContext, Camera[]) (at Assets/Retro3DPipeline-master/Assets/Retro3D/Retro3DPipeline.cs:70)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I'm learning Scriptable Rendering Pipeline. I get that error.

**Comment by KarlG-03** [comment]
Commented this line
_cb.GetTemporaryRT(rtID, rtDesc);
and code did run.
maybe API changed or something.

can I contact you by mail or something? just need some help with SRP's 🗡

**Comment by keijiro** [comment]
Sorry for the delay in response. This issue is fixed in the latest updates.
