### ISSUE TITLE
Editor errors and black screen bug

### ISSUE THREAD

**Issue by EmeraldEelEntertainment** [keijiro/Retro3DPipeline#2]
I imported this rendering pipeline to a new project and it doesn't work. I get many errors and the Scene window has a weird black filter over it, obscuring some helpful editor GUIs. I'm using the current stable build of Unity 2018.

**Comment by keijiro** [comment]
Actually I'm not sure what the root cause is, this might be related to the temporary RT format issue (#1), which is fixed in the latest updates.

**Comment by keijiro** [comment]
I'm closing this ticket. Please feel free to reopen if it sill reproduces.
